sf: 4
model:
  base_learning_rate: 5.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusionCogAdapter
  params:
    # parameterization: "v"
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 512
    channels: 4
    cond_stage_trainable: False   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    unfrozen_diff: False
    random_size: False
    time_replace: 1000
    use_usm: True
    #P2 weighting, we do not use in final version
    p2_gamma: ~
    p2_k: ~
    # use_fp16: True
    # ignore_keys: []
    drop_rate: 0.5

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPImageTokenEmbedder
      params:
        freeze: True
        layer: "penultimate"

    pre_sr_config:
      target: basicsr.archs.srresnet_arch.MSRResNet
      params:
        upscale: 4

    cog_enc_config:
      target: ldm.models.global_adapter.CogAdapter
      params:
        num_query_token: 50
        vision_width: 1024
        cross_attention_freq: 2
        num_hidden_layers: 12


degradation:
  # the first degradation process
  resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
  resize_range: [0.3, 1.5]
  gaussian_noise_prob: 0.5
  noise_range: [1, 15]
  poisson_scale_range: [0.05, 2.0]
  gray_noise_prob: 0.4
  jpeg_range: [60, 95]

  # the second degradation process
  second_blur_prob: 0.5
  resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
  resize_range2: [0.6, 1.2]
  gaussian_noise_prob2: 0.5
  noise_range2: [1, 12]
  poisson_scale_range2: [0.05, 1.0]
  gray_noise_prob2: 0.4
  jpeg_range2: [60, 100]

  gt_size: 512
  no_degradation_prob: 0.01

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 24
    num_workers: 6
    wrap: false
    train:
      target: basicsr.data.realesrgan_dataset.RealESRGANCapRefDataset
      params:
        queue_size: 180
        gt_path: PATH_FOR_GT
        meta_info: data/ImageNet/Obj512_all/train.txt
        caption_path: data/ImageNet/Obj512_all/blip2_imagenet_captions_all.json
        reference_path: data/ImageNet/Obj512_all/imagenet_all_clipcls.pkl
        reference_select_num: 10
        drop_rate: 0
        image_type: JPEG
        crop_size: 512
        io_backend:
          type: disk

        blur_kernel_size: 21
        kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
        kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
        sinc_prob: 0.1
        blur_sigma: [0.2, 1.5]
        betag_range: [0.5, 2.0]
        betap_range: [1, 1.5]

        blur_kernel_size2: 11
        kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
        kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
        sinc_prob2: 0.1
        blur_sigma2: [0.2, 1.0]
        betag_range2: [0.5, 2.0]
        betap_range2: [1, 1.5]

        final_sinc_prob: 0.8

        gt_size: 512
        use_hflip: True
        use_rot: False
        
    validation:
      target: basicsr.data.paired_image_dataset.PairedImageCapRefDataset
      params:
        dataroot_gt: PATH_FOR_GT
        dataroot_lq: PATH_FOR_LR
        meta_info: data/ImageNet/Obj512_all/val.txt
        caption_path: data/ImageNet/Obj512_all/blip2_imagenet_captions_all.json
        reference_path: data/ImageNet/Obj512_all/imagenet_all_clipcls.pkl
        reference_select_num: 10
        drop_rate: 0
        gt_size: 512
        scale: 4
        phase: val
        io_backend:
          type: disk

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 750

  trainer:
    benchmark: True
    max_steps: 20000
    limit_val_batches: 1.0
    num_sanity_val_steps: -1
